# Discord API settings
discord:
  token: "TOKEN"                        # Provide your token here

# Bot settings        
options:        
  logging:                              
    # WARNING! if you diable all logging and something breaks, fixing it will be very difficult. 
    # Recommend you leave console logging enabled as a minimum
    logToConsole: True                  # Enable logging to console
    logToFile: False                    # Enable logging  to file
    logFilePath: "path/to/log.txt"      # Log location

